import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Meal Inspiration</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className="primary-header">
          <div className="container">
            <Link href="/">
              <img src="/cooking.png" alt="MI-logo" />
            </Link>
            <div className="font-size-lg text-lg text-text_accent_400">
              Meal Inspiration
            </div>
            <button className="btn btn-main">Login</button>
          </div>
        </header>
        <div className="body">
          <section>
            <div className="container">
              <div className="even-columns">
                <div>
                  <h1 className="text-fs_primary_heading font-fw_bold">
                    Slogan goes here
                  </h1>
                  <p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                    Ducimus sapiente praesentium, earum, adipisci nesciunt
                    aspernatur eos et at vero exercitationem asperiores
                    repellendus molestias voluptatem, laboriosam beatae deserunt
                    officia necessitatibus accusantium.
                  </p>
                  <button className="btn btn-main">Login</button>
                </div>
                <div>
                  <img src="/pasta.webp" alt="pasta" />
                </div>
              </div>
            </div>
          </section>
          <section>
            <div className="container">
              <div className="even-columns"></div>
              <div>
                <h2 className="text-fs_secondary_heading font-fw_bold">
                  smaller title goes here
                </h2>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Error
                  impedit maxime nisi consequuntur totam porro nihil, rerum fuga
                  odit culpa amet illo eaque laudantium tenetur repellat ratione
                  voluptate voluptas temporibus!
                </p>
                <ul className="numbered-items" role="list">
                  <li>
                    <h3 className="font-fw_bold text-base">One</h3>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Alias error eveniet illo, voluptate architecto laborum non
                      deleniti eos commodi numquam odit. Culpa ipsa soluta
                      assumenda?
                    </p>
                  </li>
                  <li>
                    <h3 className="font-fw_bold text-base">Two</h3>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Alias error eveniet illo, voluptate architecto laborum non
                      deleniti eos commodi numquam odit. Culpa ipsa soluta
                      assumenda?
                    </p>
                  </li>
                  <li>
                    <h3 className="font-fw_bold text-base">Three</h3>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Alias error eveniet illo, voluptate architecto laborum non
                      deleniti eos commodi numquam odit. Culpa ipsa soluta
                      assumenda?
                    </p>
                  </li>
                </ul>
              </div>
              <div></div>
            </div>
          </section>
          <section className="carousel">
            <h2 className="text-fs_secondary_heading">
              Catch phrases goes here
            </h2>
            <button></button>
            {/* button needs to be extract using @apply */}
          </section>
          <section className="bg-bg_accent_400 text-text_neutral_100">
            <div className="container">
              <div className="even-columns">
                <div>
                  <p className="text-fs_secondary_heading font-fw_bold">
                    Call to Action slogan goes here
                  </p>
                </div>
                <div>
                  <button
                    className="btn btn-main bg-bg_accent_100 text-text_accent_400"
                    data-type="inverted"
                  >
                    Get Started
                  </button>
                </div>
              </div>
            </div>
          </section>
        </div>
        <footer className="text-text bg-bg_neutral_900 text-text_accent_100">
          <div className="container">
            <div className="even-columns">
              <div>
                <Link href="/">
                  <img src="/cooking.png" alt="logo" />
                </Link>
                <ul role="list" aria-label="social links">
                  <li>
                    <Link href="#" aria-aria-label="facebook"></Link>
                  </li>
                  <li>
                    <Link href="#" aria-aria-label="youtube"></Link>
                  </li>
                  <li>
                    <Link href="#" aria-aria-label="twitter"></Link>
                  </li>
                  <li>
                    <Link href="#" aria-aria-label="pinterest"></Link>
                  </li>
                  <li>
                    <Link href="#" aria-aria-label="instagram"></Link>
                  </li>
                </ul>
              </div>
              <div>
                <nav aria-label="Footer" className="footer-nav">
                  <ul role="list">
                    <li>
                      <a href="#"></a>
                    </li>
                    <li>
                      <a href="#"></a>
                    </li>
                    <li>
                      <a href="#"></a>
                    </li>
                    <li>
                      <a href="#"></a>
                    </li>
                    <li>
                      <a href="#"></a>
                    </li>
                    <li>
                      <a href="#"></a>
                    </li>
                    <li>
                      <a href="#"></a>
                    </li>
                  </ul>
                </nav>
              </div>
              <div></div>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
